<?php
/**
 * Created by PhpStorm.
 * User: chain.wu
 * Date: 2017/4/1
 * Time: 10:29
 */

namespace App\EbayApi\Component;


use App\Models\ProdCategory;

class EbayReturn extends EbayComponent
{
    public static function create($config = array(), $className = __CLASS__)
    {
        return parent::create($config, $className); // TODO: Change the autogenerated stub
    }

    /**
     * @param $maker
     * @param $name
     * @param $component
     * @return string
     */
    public function getReturnType($maker, $name, $component)
    {
        //If it is a digital camera, print out not returnabl
        $softwareCatStr      = $this->_getCatChildrenStr(232); //not exist
        $gameCatStr          = $this->_getCatChildrenStr(365);    //not exist
        //$serverMBCatStr      = $this->_getCatChildrenStr(223); //Motherboards- server change remove on 11/03/2016
        $bareSysCatStr       = $this->_getCatChildrenStr(208);  //Barebones Systems
        $bareServerCatStr    = $this->_getCatChildrenStr(209); //Server Barebones
        $completeNBCatStr    = $this->_getCatChildrenStr(57);  //Notebook Computers
        $bareNBCatStr        = $this->_getCatChildrenStr(577);    //Notebook Barebones
        $newSoftwareCatStr   = $this->_getCatChildrenStr(581); //Software
        $desktopServerCatStr = $this->_getCatChildrenStr(240);
        $netBooksCatStr      = $this->_getCatChildrenStr(686);//netbooss
        $laptopCatStr        = $this->_getCatChildrenStr(759);//ultrabooks
        $tabletsCatStr       = $this->_getCatChildrenStr(744);//tablets
        if($maker == 'Apple'){
            $returns = 'NotAccepted';
        }elseif(($component == 686) || ($component == 121) ||
            stristr($softwareCatStr, ":" . $component . ":") ||
            stristr($gameCatStr,":".$component.":") ||
            //stristr($serverMBCatStr,":".$component.":") || change MB to return accepted on 11/03/2016
            stristr($bareSysCatStr,":".$component.":") ||
            stristr($bareServerCatStr,":".$component.":") ||
            stristr($completeNBCatStr,":".$component.":") ||
            stristr($bareNBCatStr,":".$component.":") ||
            stristr($newSoftwareCatStr,":".$component.":") ||
            stristr($desktopServerCatStr,":".$component.":") ||
            stristr($tabletsCatStr,":".$component.":") ||
            stristr($laptopCatStr,":".$component.":") ||
            stristr($netBooksCatStr,":".$component.":") ||
            $name=="POP-A100" || $name=="POP-A110"){
            $returns = 'NotAccepted';
        }else{
            $returns = 'Accepted';
        } // end if

        return $returns;

    }

    /**
     * get catid path, like 1:232:45
     * @param $catid
     * @return string
     */
    private function _getCatChildrenStr($catid)
    {
        $rtn = ':';
        $data = ProdCategory::select('catid')->where('ids','like',"%:$catid:%")->get();
        foreach ($data as $v) {
            $rtn .= $v->catid . ':';
        }
        return $rtn;
    }
}