<?php
/**
 * Created by PhpStorm.
 * User: chain.wu
 * Date: 2017/4/1
 * Time: 10:08
 */

namespace App\EbayApi\Component;


class EbayCondition extends EbayComponent
{
    public $condition = array('1000','3000','2000');

    public static function create($config = array(), $className = __CLASS__)
    {
        return parent::create($config, $className); // TODO: Change the autogenerated stub
    }
    public function getConditionId($part,$title='')
    {
        $pob = \DB::table('product_openbox')->select('type')->where('part',$part)->first();
        if(count($pob) > 0){
            $conditonId = $this->condition[$pob->type];
        }else{
            if(preg_match('/oem/i', $title))
                $conditonId = 1500;
            elseif(preg_match('/Factory Recertified/i',$title) || preg_match('/(Refurbished)/i',$title))
            $conditonId = $this->condition[2];
            else
                $conditonId = $this->condition[0];
        }
        return $conditonId;
    }
}