<?php

namespace App\Providers;

use App\Events\DescSaved;
use App\Events\Event;
use Laravel\Lumen\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        /*'App\Events\SomeEvent' => [
            'App\Listeners\EventListener',
        ],*/
        'App\Events\DescSaved' => [
            'App\Listeners\SaveExRecord',
        ],
    ];
    public function boot(DescSaved $event)
    {
        parent::boot($event); // TODO: Change the autogenerated stub
    }
}
